# -*- coding: utf-8 -*-
"""BotYolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WR3pFcEkECGUyzjLy1g-5qGfpuSWWSS
"""

!pip install ultralytics
from collections import Counter



class BotImagem(BotTelegram):
  def __init__(self):
    super().__init__()
    print('Carregando identificador de imagem, aguarde...')
    self.__modelo = YOLO('yolov8n.pt')
    self.tradutor = {'person': 'pessoa', 'car': 'carro', 'dog': 'cachorro', 'cat': 'gato'}

  def identificar_arquivo(self, imagem):
    identificador = self.__modelo.predict(source=imagem, conf = 0.5)

    solucao_final = identificador[0]

    objetos_observados = []

    for objeto in solucao_final.boxes.cls:
      nome_ingles = solucao_final.names[int(objeto)]
      nome_pt = self.tradutor.get(nome_ingles, nome_ingles)
      objetos_observados.append(nome_pt)
    contagem = Counter(objetos_observados)


    if len(contagem) == 0:
      return 'Nada foi encontrado na imagem!'
    else:
      texto_resposta = 'Análise Finalizada! Foram encontrados:\n'
      for objeto, quantidade in contagem.items():
        texto_resposta += f'{objeto}: {quantidade}\n'
      return texto_resposta

# 1. Instancia a classe (agora sem passar argumentos, pois arrumamos o __init__)
bot = BotImagem()

# 2. Usa uma URL pública limpa para testar
# (Aquele código gigante anterior daria erro)
url_teste = "https://img.freepik.com/fotos-gratis/de-perto-as-pessoas-a-ficarem-mais-fortes-juntas_23-2149125872.jpg?semt=ais_hybrid&w=740&q=80"

print("Processando imagem...")
lista = bot.identificar_arquivo(url_teste)

print("--- RESULTADO ---")
print("O bot viu:", lista)